# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ca495591d954d13f659edbc91800a4999e3a9ecf5aadb2715a73be6dde0e98eae86d3ee181236e80a1d8adbf3afe316ee537831bae798725a77361d2a2a7b77

test:
  secret_key_base: d5f0f933db7b09e077d12c07f56b84936f94f2dc64422b8058af8f212b0db08326a2653cc3234d785658cd3bb40e4c4c42c8900d4f7a8c8fd94f97245c3e9fd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
